<?php /** @var Riksten\PreviousTabCAP\Block\RelatedProducts $block */ ?>
<?php $productIds = $block->getRelatedProductCollection() ?>
<?php $image = 'new_products_content_widget_grid' ?>
<?php $product = 0 ?>
<div class="related-products-title">
    <h2><?= __('Related Products') ?></h2>
</div>
<div class="products wrapper grid products-grid">
    <ol class="products list items product-items">
    <?php foreach ($productIds as $productId): ?>
        <?php if($product++ == 4) break ?>
        <li class="product-item">
            <div class="product-item-info" data-container="product-grid">
                <a href="<?= $productId->getProductUrl() ?>" class="product-item-photo">
                    <?= $block->getImage($productId, $image)->toHtml() ?>
                </a>
                <div class="product details product-item-details">
                    <strong class="product name product-item-name">
                        <a class="product-item-link" href="<?= $productId->getProductUrl() ?>">
                            <?= $productId->getName() ?>
                        </a>
                    </strong>
                    <div class="price-box price-final_price">
                        <span class="price"><?= $productId->getFormatedPrice() ?></span>
                    </div>
                </div>
            </div>
        </li>
        <?php endforeach ?>
    </ol>
</div>